app: gin_main
stack: api
server:
  port: 8080
  read_header_timeout: 5s
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 15s
database:
  bookDB: postgresql://admin:admin@localhost:5432/BooksWarehouse
jwt:
  secret_key: kf23jfs0jf191j09wfj09hr0921h0h20w1h09wfw1241241rwqrdq1091jd
  ttl: 1h